version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Coti2024!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
       - "27017:27017"
    volumes:
       - mongodb_data:/data/db
    networks:
       - mynetwork

volumes:
  sqlserver_data:
  mongodb_data:

networks:
  mynetwork:
   driver: bridge